In [2]:
     import numpy as np
X= np.array(([2,9],[1,5],[3,6]), dtype=float)
y= np.array(([92],[86],[89]), dtype=float)
print(X)
print(y)
    #x=X.np.amax(X,axis=0)
    #y=y/100;      #max marks in 100

class Neural_Network(object):
        def __init__(self):
            self.inputsize=2
            self.outputsize=1
            self.hiddensize=3
            self.W1=np.random.rand(self.inputsize,self.hiddensize)
            self.W2=np.random.rand(self.hiddensize,self.outputsize)
            print(self.W1) 
            print(self.W2)
            
        def forward(self,X):
         #forward propagation
            self.z=np.dot(X,self.W1)
            self.z1=self.sigmoid(self.z)
            self.z2=np.dot(self.z1,self.W2)
            o=self.sigmoid(self.z2)
            return o*100    #had to multiply by 100

        def sigmoid(self,s):
            return 1/(1+np.exp(-s))

        
NN=Neural_Network()
o=NN.forward(X)

print("Predicted output\n" +str(o))
print("Actual Output \n" + str(y))

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]
[[0.06993189 0.81053904 0.91735321]
 [0.22411612 0.61548841 0.80166258]]
[[0.59520159]
 [0.33653677]
 [0.54714391]]
Predicted output
[[80.4842858 ]
 [79.07417234]
 [79.80316274]]
Actual Output 
[[92.]
 [86.]
 [89.]]


In [10]:
     import numpy as np
X= np.array(([2,9],[1,5],[3,6]), dtype=float)
y= np.array(([92],[86],[89]), dtype=float)
#print(X)
#print(Y)
    #x=X.np.amax(X,axis=0)
    #y=y/100;      #max marks in 100

class Neural_Network(object):
        def __init__(self):
            self.inputsize=2
            self.outputsize=1
            self.hiddensize=3
            self.W1=np.random.rand(self.inputsize,self.hiddensize)
            self.W2=np.random.rand(self.hiddensize,self.outputsize)
            #print(self.W1) 
            #print(self.W2)
            
        def forward(self,X):
         #forward propagation
            self.z=np.dot(X,self.W1)
            self.z1=self.sigmoid(self.z)
            self.z2=np.dot(self.z1,self.W2)
            o=self.sigmoid(self.z2)
            return o

        def sigmoid(self,s):
            return 1/(1+np.exp(-s))

        
        def sigmoidprime(self,s):
            return s*(1-s)

        def backward(self,X,y,o):
            print("inside backward")
            self.o_error=y-o;
            self.o_delta=self.o_error*self.sigmoidprime(o)
    
            self.z2_error=self.o_delta.dot(self.W2.T)
            self.z2_delta=self.z2_error*self.sigmoidprime(self.z2)
    
            self.W1+=X.T.dot(self.z2_delta)   #input to hidden weights
            self.W2+=self.z2.T.dot(self.o_delta)  # hidden to output weights  
    
        def train(self,X,y):
            print('\ntrain')
            print(str(X))
            print(str(o))
            self.backward(X,y,o)
    
NN = Neural_Network()
for i in range(2): 
    print ("Input: \n" + str(X) )
    print ("Actual Output: \n" + str(y))
    o=NN.forward(X)
    print ("Predicted Output: \n" + str(o)) 
    print ("Loss: \n" + str(np.mean(np.square(y - 100*NN.forward(X))))) # mean sum squared loss
    print ("\n")
    NN.train(X, y)

Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[92.]
 [86.]
 [89.]]
Predicted Output: 
[[0.86687417]
 [0.86413018]
 [0.86651563]]
Loss: 
11.303093078696579



train
[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[0.86687417]
 [0.86413018]
 [0.86651563]]
inside backward
Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[92.]
 [86.]
 [89.]]
Predicted Output: 
[[0.5]
 [0.5]
 [0.5]]
Loss: 
1527.0



train
[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[0.5]
 [0.5]
 [0.5]]
inside backward


In [11]:
     import numpy as np
X= np.array(([2,9],[1,5],[3,6]), dtype=float)
y= np.array(([92],[86],[89]), dtype=float)
#print(X)
#print(Y)
    #x=X.np.amax(X,axis=0)
    #y=y/100;      #max marks in 100

class Neural_Network(object):
        def __init__(self):
            self.inputsize=2
            self.outputsize=1
            self.hiddensize=3
            self.W1=np.random.rand(self.inputsize,self.hiddensize)
            self.W2=np.random.rand(self.hiddensize,self.outputsize)
            #print(self.W1) 
            #print(self.W2)
            
        def forward(self,X):
         #forward propagation
            self.z=np.dot(X,self.W1)
            self.z1=self.sigmoid(self.z)
            self.z2=np.dot(self.z1,self.W2)
            o=self.sigmoid(self.z2)
            return o

        def sigmoid(self,s):
            return 1/(1+np.exp(-s))

        
        def sigmoidprime(self,s):
            return s*(1-s)

        def backward(self,X,y,o):
            print("inside backward")
            #print(str(o))
            self.o_error=y-o*100;
            print('o_error'+str(self.o_error))
            self.o_delta=self.o_error*self.sigmoidprime(o)
            print('o_delta'+str(self.o_delta))
            self.z2_error=self.o_delta.dot(self.W2.T)
            self.z2_delta=self.z2_error*self.sigmoidprime(self.z2)
            print('z error' +str(self.z2_error))
            print('z d error' +str(self.z2_delta))
            print('weights before'+str(self.W1))
            print(str(self.W2))
            self.W1+=X.T.dot(self.z2_delta)   #input to hidden weights
            self.W2+=self.z2.T.dot(self.o_delta)  # hidden to output weights  
            print('weights after'+str(self.W1))
            print(str(self.W2))
            
    
        def train(self,X,y):
            print('\ntrain')
            #print(str(X))
            o=self.forward(X)
           # print(str(o))
            self.backward(X,y,o)
    
NN = Neural_Network()
for i in range(2): # trains the NN 1,000 times
    print ("Input: \n" + str(X) )
    print ("Actual Output: \n" + str(y))
    print ("Predicted Output: \n" + str((NN.forward(X)))) 
    print ("Loss: \n" + str(np.mean(np.square(y - 100*NN.forward(X))))) # mean sum squared loss
    print ("\n")
    NN.train(X, y)

Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[92.]
 [86.]
 [89.]]
Predicted Output: 
[[0.85664806]
 [0.83115426]
 [0.85613813]]
Loss: 
19.973905323036814



train
inside backward
o_error[[6.3351942 ]
 [2.88457411]
 [3.38618702]]
o_delta[[0.77797555]
 [0.40481206]
 [0.41706187]]
z error[[0.42630284 0.41491967 0.61622314]
 [0.22182257 0.21589944 0.32064576]
 [0.22853502 0.22243266 0.33034865]]
z d error[[-0.60033424 -0.58430407 -0.86778651]
 [-0.20994703 -0.20434101 -0.30347961]
 [-0.31939433 -0.31086584 -0.46168629]]
weights before[[0.99897164 0.27406229 0.60698806]
 [0.08273869 0.20248482 0.39069179]]
[[0.54796432]
 [0.53333253]
 [0.79208549]]
weights after[[ -1.36982688  -2.03148437  -2.81712344]
 [ -8.28637068  -7.94315189 -11.70690259]]
[[3.3278342 ]
 [3.31320241]
 [3.57195537]]
Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[92.]
 [86.]
 [89.]]
Predicted Output: 
[[0.5]
 [0.5]
 [0.5]]
Loss: 
1527.0



train
inside backward
o_error[[42.]
 [36.]
 [39.]]
o_delta[[10.5 ]
